spring:
  datasource:
    url: jdbc:postgresql://postgres:vysrLnxg9esaWhLPJPlF@containers-us-west-136.railway.app:7744/railway
      username: ${PGUSER}
      password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create